<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="MSI" failures="1" tests="15" name="FirstTest" time="49.146" errors="0" timestamp="2024-12-05T18:06:17 IST" skipped="0">
  <testcase classname="FirstTest" name="prepareBaseline" time="4.093"/>
  <testcase classname="FirstTest" name="prepareBaseline" time="4.822"/>
  <testcase classname="FirstTest" name="prepareBaseline" time="3.285"/>
  <testcase classname="FirstTest" name="compareImages" time="0.334">
    <failure message="The screenshots do not match! expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The screenshots do not match! expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at FirstTest.compareImages(FirstTest.java:72)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- compareImages -->
  <testcase classname="FirstTest" name="prepareBaseline" time="3.569"/>
  <testcase classname="FirstTest" name="test" time="0.926"/>
  <testcase classname="FirstTest" name="prepareBaseline" time="1.502"/>
  <testcase classname="FirstTest" name="prepareBaseline" time="5.158"/>
  <testcase classname="FirstTest" name="prepareBaseline" time="3.119"/>
  <testcase classname="FirstTest" name="compareImagesToFail" time="0.243"/>
  <testcase classname="FirstTest" name="prepareBaseline" time="3.407"/>
  <testcase classname="FirstTest" name="prepareBaseline" time="6.146"/>
  <testcase classname="FirstTest" name="prepareBaseline" time="4.465"/>
  <testcase classname="FirstTest" name="prepareBaseline" time="4.354"/>
  <testcase classname="FirstTest" name="prepareBaseline" time="3.723"/>
</testsuite> <!-- FirstTest -->
